language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -e "git+https://github.com/ranger/ranger.git@master#egg=ranger-fm"
  - pip install flake8
script:
  - python setup.py test
  - flake8
notifications:
  email:
    - hankei6km+travis@gmail.com
